import { CivicCase, Ward, ActivityFeedItem } from './types';

export const initialWards: Ward[] = [
  {
    id: 'ward-4',
    name: 'Ward 4 (Northwest Heights)',
    councilor: 'Hon. Eleanor Vance',
    accountabilityScore: 92,
    totalCases: 148,
    activeCases: 12,
    resolvedCases: 136,
    resolutionRate: 91.8,
    averageResolutionDays: 3.4,
    ranking: 1,
  },
  {
    id: 'ward-7',
    name: 'Ward 7 (Downtown Core)',
    councilor: 'Hon. Marcus Brody',
    accountabilityScore: 78,
    totalCases: 234,
    activeCases: 51,
    resolvedCases: 183,
    resolutionRate: 78.2,
    averageResolutionDays: 6.8,
    ranking: 2,
  },
  {
    id: 'ward-2',
    name: 'Ward 2 (Riverfront South)',
    councilor: 'Hon. David Kuan',
    accountabilityScore: 71,
    totalCases: 165,
    activeCases: 48,
    resolvedCases: 117,
    resolutionRate: 70.9,
    averageResolutionDays: 8.1,
    ranking: 3,
  },
  {
    id: 'ward-12',
    name: 'Ward 12 (East Industrial)',
    councilor: 'Hon. Sarah Jenkins',
    accountabilityScore: 49,
    totalCases: 312,
    activeCases: 149,
    resolvedCases: 163,
    resolutionRate: 52.2,
    averageResolutionDays: 14.5,
    ranking: 4,
  },
];

export const initialCases: CivicCase[] = [
  {
    id: 'case-101',
    title: 'Water Main Fracture & Street Flooding',
    description: 'A massive water main split has occurred under the intersection of Pine Street and 14th Ave, causing localized street flooding, low water pressure in adjacent residential buildings, and active erosion of the subgrade. Water is flowing at an estimated 200 gallons per minute.',
    category: 'Utilities',
    location: 'Pine St & 14th Ave, Northwest Heights',
    wardId: 'ward-4',
    wardName: 'Ward 4 (Northwest Heights)',
    severity: 'Critical',
    status: 'In Progress',
    reportedAt: '2026-06-24T08:15:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1542060748-10c28b629f6f?auto=format&fit=crop&q=80&w=800',
    communityVerifications: 34,
    upvotes: 89,
    rootCauseAnalysis: {
      identifiedProblem: 'Structural failure of a 12-inch cast iron water main originally installed in 1954.',
      systemicIssue: 'Exceeded historical design life combined with soil movement from recent heavy rainfall.',
      actionTaken: 'Isolated water flow to the broken section, dispatched emergency excavation crews, and re-routed clean water distribution pipelines to restore local pressures.',
      preventativeMeasure: 'Flagged this 4-block corridor for the FY2027 Pipe Replacement Program; adjusted pressure relief valves upstream to prevent sudden hydraulic shock.',
      aiConfidence: 96,
    },
    timeline: [
      {
        id: 'evt-1',
        status: 'reported',
        title: 'Case Logged via AI Mobile Analysis',
        description: 'Resident uploaded photo. System automatically extracted GPS coordinates, categorized as "Utilities - Water Main Fracture", and flagged severity as "Critical".',
        timestamp: '2026-06-24T08:15:00Z',
        actor: 'CaseZero Engine',
      },
      {
        id: 'evt-2',
        status: 'assigned',
        title: 'Municipal Water Dispatch Notified',
        description: 'Automated high-priority API notification sent directly to Ward 4 Utility maintenance queue.',
        timestamp: '2026-06-24T08:18:00Z',
        actor: 'CaseZero Dispatcher',
      },
      {
        id: 'evt-3',
        status: 'investigating',
        title: 'Crew On-Site & Isolation Initiated',
        description: 'Field engineer confirmed failure. Shut-off valves localized to Pine St. Water flow stopped.',
        timestamp: '2026-06-24T09:30:00Z',
        actor: 'Crew #12 (Muni Water)',
      },
    ],
  },
  {
    id: 'case-102',
    title: 'Hazardous Waste & Illegal Dumping',
    description: 'Multiple rusted metal barrels, household construction debris, and car batteries have been illegally dumped at the edge of Cedar Ravine. Strong chemical smell present. Potential runoff into the municipal creek bed below.',
    category: 'Sanitation',
    location: 'End of Cedar Ravine Road, East Industrial',
    wardId: 'ward-12',
    wardName: 'Ward 12 (East Industrial)',
    severity: 'High',
    status: 'Open',
    reportedAt: '2026-06-25T06:40:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
    communityVerifications: 15,
    upvotes: 56,
    rootCauseAnalysis: {
      identifiedProblem: 'Unauthorized commercial dumping of household batteries and motor solvents in unmonitored dead-end road.',
      systemicIssue: 'Lack of neighborhood illumination and vehicle barriers on the perimeter of Cedar Ravine Conservation Area.',
      actionTaken: 'Scheduled environmental hazardous material extraction. Municipal police notified for camera surveillance check.',
      preventativeMeasure: 'Install steel gate barrier at dead-end road; add solar-powered motion-activated cameras and "Fine $10,000" signage.',
      aiConfidence: 89,
    },
    timeline: [
      {
        id: 'evt-4',
        status: 'reported',
        title: 'Hazardous Dumping Reported',
        description: 'User reported multiple toxic waste elements. Photo verified automatically with high toxicity index matching.',
        timestamp: '2026-06-25T06:40:00Z',
        actor: 'Civic Reporter App',
      },
    ],
  },
  {
    id: 'case-103',
    title: 'Damaged Pedestrian Guardrail',
    description: 'The steel safety guardrail dividing the high-speed cross-town connector from the sidewalk at 5th & Main has been heavily deformed, likely by a vehicular impact. Sharp metal edges protrude directly into the walking path, presenting immediate danger to school children.',
    category: 'Public Safety',
    location: 'Intersection of 5th Ave & Main St, Downtown Core',
    wardId: 'ward-7',
    wardName: 'Ward 7 (Downtown Core)',
    severity: 'High',
    status: 'Resolved',
    reportedAt: '2026-06-21T14:20:00Z',
    resolvedAt: '2026-06-23T11:00:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    communityVerifications: 42,
    upvotes: 112,
    rootCauseAnalysis: {
      identifiedProblem: 'Deformed structural guardrail from vehicle collision.',
      systemicIssue: 'Lack of speed-calming measures on high-density pedestrian school zone adjacent to highway exit.',
      actionTaken: 'Removed damaged steel section, anchored new high-grade galvanized steel posts, and repaved concrete base block.',
      preventativeMeasure: 'Submitted request for dynamic radar speed-indicator sign 150 feet prior to intersection.',
      aiConfidence: 94,
    },
    timeline: [
      {
        id: 'evt-5',
        status: 'reported',
        title: 'Collision Guardrail Damaged',
        description: 'Case registered. Protruding sharp metal identified as critical pedestrian hazard.',
        timestamp: '2026-06-21T14:20:00Z',
        actor: 'Citizen App Portal',
      },
      {
        id: 'evt-6',
        status: 'assigned',
        title: 'Assigned to Public Works Department',
        description: 'Emergency Work Order #9901 issued.',
        timestamp: '2026-06-21T15:00:00Z',
        actor: 'CaseZero Dispatcher',
      },
      {
        id: 'evt-7',
        status: 'investigating',
        title: 'Site Safety Inspection',
        description: 'Temporary orange warning cones and hazard tape placed to redirect sidewalk traffic.',
        timestamp: '2026-06-22T08:30:00Z',
        actor: 'Inspector J. Miller',
      },
      {
        id: 'evt-8',
        status: 'resolved',
        title: 'Guardrail Fully Restored & Signed Off',
        description: 'Welding completed, new guardrail components secured. Walkway safe and clear.',
        timestamp: '2026-06-23T11:00:00Z',
        actor: 'Public Works Crew B',
      },
    ],
  },
  {
    id: 'case-104',
    title: 'Traffic Signal Controller Failure',
    description: 'The traffic lights at Broadway & Elm are stuck on a permanent red cycle for east-west traffic, causing massive vehicular grids and angry horn-honking. Drivers are beginning to dangerously run the red light.',
    category: 'Traffic',
    location: 'Broadway St & Elm Ave, Northwest Heights',
    wardId: 'ward-4',
    wardName: 'Ward 4 (Northwest Heights)',
    severity: 'High',
    status: 'In Progress',
    reportedAt: '2026-06-25T09:10:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1510985834114-ff994646a782?auto=format&fit=crop&q=80&w=800',
    communityVerifications: 28,
    upvotes: 95,
    rootCauseAnalysis: {
      identifiedProblem: 'Relay failure within the solid-state controller cabinet, preventing signal cycle triggers.',
      systemicIssue: 'Aging controller hardware cabinet that has not had a solid-state board upgrade in 12 years.',
      actionTaken: 'Dispatched traffic light technician, switched intersections to temporary yellow-flashing emergency bypass.',
      preventativeMeasure: 'Scheduled signal cabinet for full controller card upgrade next month during routine system maintenance.',
      aiConfidence: 91,
    },
    timeline: [
      {
        id: 'evt-9',
        status: 'reported',
        title: 'Stuck Traffic Signal Logged',
        description: 'Multiple automated alerts received from smart vehicle dashcams and verified by citizen uploads.',
        timestamp: '2026-06-25T09:10:00Z',
        actor: 'CaseZero AI',
      },
      {
        id: 'evt-10',
        status: 'investigating',
        title: 'Technician Dispatched',
        description: 'Traffic signals engineer arrived on site, cabinet opened, diagnosed as cabinet board relay failure.',
        timestamp: '2026-06-25T10:15:00Z',
        actor: 'Eng. Carl Sterling',
      },
    ],
  },
  {
    id: 'case-105',
    title: 'Clogged Storm Drain with Tree Roots',
    description: 'The storm grate in front of 445 Lincoln Ave is completely blocked by compressed mud, plastic litter, and thick root intrusion from the neighboring sweetgum trees. It has caused significant standing water on the street during minor rain events.',
    category: 'Sanitation',
    location: '445 Lincoln Ave, East Industrial',
    wardId: 'ward-12',
    wardName: 'Ward 12 (East Industrial)',
    severity: 'Medium',
    status: 'Resolved',
    reportedAt: '2026-06-18T10:00:00Z',
    resolvedAt: '2026-06-20T16:00:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1621451537084-482c730e37e6?auto=format&fit=crop&q=80&w=800',
    communityVerifications: 9,
    upvotes: 18,
    rootCauseAnalysis: {
      identifiedProblem: 'Root invasion into the lateral sewer pipe combined with catch basin debris buildup.',
      systemicIssue: 'Lack of annual preventative hydro-jetting in high-canopy street segments.',
      actionTaken: 'Sewer vacuum truck cleared catch basin, mechanical root cutters excised root blockage inside pipe, flushed line.',
      preventativeMeasure: 'Added Lincoln Ave catch basins to the bi-annual hydro-jet inspection list.',
      aiConfidence: 87,
    },
    timeline: [
      {
        id: 'evt-11',
        status: 'reported',
        title: 'Storm Drain Blockage Reported',
        description: 'Reported with photo showing water accumulation.',
        timestamp: '2026-06-18T10:00:00Z',
        actor: 'Citizen User',
      },
      {
        id: 'evt-12',
        status: 'investigating',
        title: 'Hydro-Vac Diagnostics',
        description: 'Sewer inspection camera identified root intrusion 4 feet deep inside lateral connector.',
        timestamp: '2026-06-19T13:00:00Z',
        actor: 'Sewer Dept Crew #4',
      },
      {
        id: 'evt-13',
        status: 'resolved',
        title: 'Root Cleanout & Vacuum Completed',
        description: 'Lateral cleared, water flow rate tested at 100% capacity. Grate secured.',
        timestamp: '2026-06-20T16:00:00Z',
        actor: 'Sewer Dept Crew #4',
      },
    ],
  },
  {
    id: 'case-106',
    title: 'Broken High-Pressure Sodium Streetlight',
    description: 'Streetlight pole #884 adjacent to Oak Park playground is entirely burnt out, leaving the sidewalk, crosswalk, and park entry in pitch black darkness. Local residents feel unsafe walking at night.',
    category: 'Infrastructure',
    location: 'Oak Park East Boundary, Downtown Core',
    wardId: 'ward-7',
    wardName: 'Ward 7 (Downtown Core)',
    severity: 'Low',
    status: 'Open',
    reportedAt: '2026-06-25T11:00:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1509024644558-2f56ce76c090?auto=format&fit=crop&q=80&w=800',
    communityVerifications: 3,
    upvotes: 12,
    rootCauseAnalysis: {
      identifiedProblem: 'Burnt-out streetlight bulb / faulty photocell sensor.',
      systemicIssue: 'High energy consumption and short life span of high-pressure sodium bulbs compared to LED retrofits.',
      actionTaken: 'Scheduled streetlight bucket truck dispatch for bulb replacement.',
      preventativeMeasure: 'Flagged this sector of Downtown Core for municipal LED upgrade converting all poles to low-maintenance fixtures.',
      aiConfidence: 95,
    },
    timeline: [
      {
        id: 'evt-14',
        status: 'reported',
        title: 'Streetlight Blackout Reported',
        description: 'Report logged. High-pressure sodium signature detected in metadata.',
        timestamp: '2026-06-25T11:00:00Z',
        actor: 'Citizen Reporter App',
      },
    ],
  }
];

export const initialActivities: ActivityFeedItem[] = [
  {
    id: 'act-1',
    caseId: 'case-101',
    caseTitle: 'Water Main Fracture & Street Flooding',
    type: 'status_change',
    message: 'Utility crew dispatched to isolate water main split at Pine & 14th.',
    timestamp: '2026-06-24T09:30:00Z',
    user: 'Muni Utilities Dispatch',
  },
  {
    id: 'act-2',
    caseId: 'case-102',
    caseTitle: 'Hazardous Waste & Illegal Dumping',
    type: 'reported',
    message: 'New Critical Issue reported at Cedar Ravine: Illegal Toxic Dumping.',
    timestamp: '2026-06-25T06:40:00Z',
    user: 'Alek S. (Verified Resident)',
  },
  {
    id: 'act-3',
    caseId: 'case-103',
    caseTitle: 'Damaged Pedestrian Guardrail',
    type: 'resolved',
    message: 'Pedestrian guardrail at 5th & Main fully restored and signed off.',
    timestamp: '2026-06-23T11:00:00Z',
    user: 'Public Works Department',
  },
  {
    id: 'act-4',
    caseId: 'case-104',
    caseTitle: 'Traffic Signal Controller Failure',
    type: 'verified',
    message: 'Signal failure at Broadway & Elm verified by 28 local residents.',
    timestamp: '2026-06-25T10:30:00Z',
    user: 'CaseZero Community',
  },
  {
    id: 'act-5',
    caseId: 'case-106',
    caseTitle: 'Broken High-Pressure Sodium Streetlight',
    type: 'reported',
    message: 'New low-priority issue reported at Oak Park playground boundary.',
    timestamp: '2026-06-25T11:00:00Z',
    user: 'Nadia P. (Citizen)',
  }
];
